### PR TITLE
feat: Added Github Workflow Greetings

### LINKED ISSUE #26: [Feature]: Add the GitHub action workflow for greeting contributors
# Description:
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull requests (PR) and issue creators, fostering a welcoming environment.

# Proposed Changes:
Implement a GitHub Action workflow that triggers new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Please assign me this issue under IWOC**

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
Closes #26

### CODE REVIEW

**Comment by ksauraj** [comment]
@JiyaGupta-cs you forgot to change repo name [here](https://github.com/ksauraj/jee_counsellor/pull/27/commits/d7e0a559de7a005fc21cc8bddf9fcfa4c2d1f8e9#diff-6318f5fc1ff2829ebbfd7846021a98d807a3b866fcfac669187f49fa22a40702R15).

**Comment by JiyaGupta-cs** [comment]
@ksauraj Sorry sir
I have fixed it now

**Comment by ksauraj** [comment]
> @ksauraj Sorry sir I have fixed it now

Ah no problem, let me check real quick.

**Comment by ksauraj** [comment]
It would be better if you change `JEE_Counsellor` to `JEE Counsellor`.

**Comment by JiyaGupta-cs** [comment]
@ksauraj Done sir

**Comment by ksauraj** [comment]
Okay everything seems good for now. I'm merging this.

**Pull request merged**
