### PR TITLE
About section Implemented.

### LINKED ISSUE #14: tool: adding a about section in the tool
In the main menu, we propose adding an **'About'** section that will showcase the current version, provide a brief overview of the tool, acknowledge contributors, and include other relevant information. This section aims to offer users a comprehensive understanding of the tool, its evolution, and the people involved in its development.

### PR DESCRIPTION
**Pull request by Tholkappiar**
### Closes
#14 

#### Thank you for your time and consideration !

### CODE REVIEW

**Comment by ksauraj** [comment]
Might require further action, but good to get merged.

**Comment by Tholkappiar** [comment]
Hey , You forgot to add up the difficulty label to the PR !

**Comment by ksauraj** [comment]
> Hey , You forgot to add up the difficulty label to the PR !

Not required in PR ig, Didn't got points or what?

**Comment by Tholkappiar** [comment]
Yeah, but  it's updated now .Thanks

**Pull request merged**
