### PR TITLE
feat: Added GitHub Workflow For Issues And Pull Requests

### LINKED ISSUE #28: Adding GitHub workflows for issue and pull request
A template is necessary for the beginners to report any issue or pull request

Please assign me this under IWOC

### PR DESCRIPTION
**Pull request by JiyaGupta-cs**
Closes #28

### CODE REVIEW

**Comment by ksauraj** [comment]
> @ksauraj Please review the PR

Yah I'm reviewing it now.

**Comment by ksauraj** [comment]
@JiyaGupta-cs do those quick changes, and ig this will be ready to get merged.

**Comment by JiyaGupta-cs** [comment]
@ksauraj Which changes ?

**Comment by JiyaGupta-cs** [comment]
@ksauraj Which changes are you referring to? You haven't told me earlier

**Comment by ksauraj** [comment]
> @ksauraj Which changes are you referring to? You haven't told me earlier

image
These changes, check those review which i gave.

**Comment by JiyaGupta-cs** [comment]
@ksauraj Done! Please review

**Review by ksauraj — COMMENTED** [review]
Actually I just wanted you to remove 
```
- label: "I have starred the repository"
          required: true
```

**Comment by ksauraj** [comment]
> Actually I just wanted you to remove
> 
> ```
> - label: "I have starred the repository"
>           required: true
> ```

If you can fix this or else I'm ready to merge this too.

**Comment by JiyaGupta-cs** [comment]
@ksauraj Fixed!!!

**Comment by ksauraj** [comment]
Great job, @JiyaGupta-cs , and thank you for being patient.

**Comment by JiyaGupta-cs** [comment]
> Great job, @JiyaGupta-cs , and thank you for being patient.

Could you please change the label to hard ?

**Comment by ksauraj** [comment]
> Could you please change the label to hard ? If you like it

I already merged it, won't count now anyway.

**Pull request merged**
