### PR TITLE
feat: added clear output directory feature

### PR DESCRIPTION
**Pull request by lakshita10341**
function for clearing output directory is added in main menu if such directory exists. Please review the PR and suggest me changes if there are any.

### CODE REVIEW

**Comment by ksauraj** [comment]
Hey that was great work, but i want to introduce some changes...
Instead of popping for cleaning out output dir everytime like this 
image
we can just put an option in the main menu, so that whenever users want to clean it they can....
image
You can add a 5th option which says clean output dir and when user selects, you display a warning and deletes it...

**Comment by lakshita10341** [comment]
okay sure, i will do this change.

**Comment by ksauraj** [comment]
Reviewing

**Comment by ksauraj** [comment]
image
Red looks ugly, could you make it better

**Comment by lakshita10341** [comment]
Do I changed the 5th option with the same blue color and the warning with magenta color?

**Comment by ksauraj** [comment]
Yah, and make it 4th optiopn and exit as 5th

**Comment by lakshita10341** [comment]
done the changes. Please review it.

**Comment by ksauraj** [comment]
Seems fine to me

**Pull request merged**
